### ISSUE TITLE
Collision export issue

### ISSUE THREAD

**Issue by enenra** [enenra/space-engineers-utilities#101]
Reported here: https://discordapp.com/channels/125011928711036928/161758345856811008/675049576461369354

![](https://cdn.discordapp.com/attachments/161758345856811008/675049572548083723/unknown.png)

![](https://cdn.discordapp.com/attachments/161758345856811008/675049935401517097/unknown.png)

![](https://cdn.discordapp.com/attachments/161758345856811008/675050304940802083/unknown.png)

BLEND file: https://discordapp.com/channels/125011928711036928/161758345856811008/675051680466993192

**Comment by cstahlhut** [comment]
Fixed, required a re-install of Havok Content Tools.
