### ISSUE TITLE
Create SBC Entry for <Center /> tag in SBC

### ISSUE THREAD

**Issue by cstahlhut** [enenra/space-engineers-utilities#110]
Request to write to XML a `<Center x="0" y="0" z="0" />` tag based on the location of an Empty on the model.

The default should be 0 ,0, 0.

This tag controls where the block is held in the 'hand' when the player is placing it and is useful for large blocks. Without some indicator from Blender to SE, its typically worked out by trial and error. 

The suggestion was to allow the placement of an 'empty' which could be used to make the SBC entry that would contain its X, Y, Z values.

**Comment by enenra** [comment]
Would need to add empty type to empty spawning operator and then read out its position on export. nbd. Moving to 0.9.0 .
