### ISSUE TITLE
Full copy on a scene and changing the subtype ID doesnt update collection 'tag'

### ISSUE THREAD

**Issue by cstahlhut** [enenra/space-engineers-utilities#117]
1.) Create a fully copy.
2.) Change subtypeid
3.) Collection 'tag' now mismatches
4.) Click re-create to correct 'tag' on collections - nothing happens.
5.) Expected behaviour - clicking re-create corrects the tag to match the subtype ID.

Might be doing some weird stuff with exports, I had it exporting a scene that was not my scene at one point after manually changing the tag on the main collection. Needs testing after being corrected.

**Comment by enenra** [comment]
I straight up cannot fix this without completely restructuring how collections are handled. And I wouldn't know how else to do it. The addon cannot handle to subtypeIds being the same and there's lots of code to prevent that from happening but I cannot hook into the scene copy, and thus I can't do shit to prevent it from also copying the subtypeId.
We'll just have to consider it something we don't support...
