### ISSUE TITLE
Icon render DDS export

### ISSUE THREAD

**Issue by enenra** [enenra/space-engineers-utilities#137]
Add link to texconv.exe and DDS export.

**Comment by chipstix213** [comment]
Changing the output to PNG format would allow the icon to go straight into the game.

**Comment by enenra** [comment]
@chipstix213 You can already select PNG as output actually. But yeah, this might be superfluous considering PNG works perfectly fine.

**Comment by enenra** [comment]
Yes, PNG works so this is kinda pointless.
