### ISSUE TITLE
[Suggestion] Grid option for bounding box.

### ISSUE THREAD

**Issue by lAimBotl** [enenra/space-engineers-utilities#191]
A grid option for bounding box, size based on block, eg: 3x3 face would be 9 cubes in the grid.

**Comment by enenra** [comment]
This would require a rewrite of the way I render the BBOX, and I barely understand that kind of code myself. In addition, I'm not confident that this would be very useful / readable as the BBOX is drawn over geometry so you would always see all the lines from any angle, making it a complete visual mess. Realistically, I'm not going to work on this anytime soon, if at all.
