### ISSUE TITLE
SEUT Release v0.9.89/v0.9.90 Outdated Dependencies

### ISSUE THREAD

**Issue by ItsOkayItsOfficial** [enenra/space-engineers-utilities#194]
SEUT Release v0.9.89 seems to be packaged with an outdated version of SETextureConverter. The [current version](https://github.com/TheWizardLizard/SETextureConverter/releases/tag/v1.3) of SETextureConverter (1.3) enables user to select SE installs outside of the default `C` drive.

**Comment by ItsOkayItsOfficial** [comment]
It doesn't seem like SEUT Release v0.9.90 fixed this. Still does not have SETextureConverter (1.3) included. 

Updating issue title to reflect.

**Comment by enenra** [comment]
I've updated the 0.9.90 release with the updated texture converter. Thanks for the report!
