### ISSUE TITLE
Not exporting main model.

### ISSUE THREAD

**Issue by A-p-o-t-h-i-c-o-n** [enenra/space-engineers-utilities#195]
When I try to export it will export everything except for the main model. If I view the console everything looks normal and it even lies about successfully exporting the MWM for the main model. It only happens on this one specific model and it happens every time I try to export it. I tried restarting blender and that didn't fix it. I also tried copying the model into a different blend file but it still has the same problem.

**Comment by enenra** [comment]
This sounds like the reason is with the model. 

Ensure you have UV maps for all surfaces, no invalid triangles, etc. 

For anything further I will need the logs and likely blend file of the model.
