### ISSUE TITLE
How to import a collision mesh?

### ISSUE THREAD

**Issue by Gohla** [enenra/space-engineers-utilities#197]
I'd like to make a mod that makes most existing SE blocks upgradable. That requires importing the models of those blocks and adding upgrade dummies to them. I can import the models from the FBX files of the SE Mod SDK, but I don't know how to import the collision meshes. It seems these are in .hkt files, but I can't figure out how to import them. How do I import those collision meshes?

I tried exporting without a collision mesh, but then the blocks just get cube bounding box collision.

Alternatively, is there a way to just copy over the collision mesh in the resulting .mwm file? I don't think I need to modify the collision shape, so that would also work for me.

**Comment by Gohla** [comment]
I found a workaround for just copying the collision data: disable "Delete Loose Files" in the export settings, and copy the .hkt file to the output directory and ensure it has the same name as the resulting .fbx file.

**Comment by enenra** [comment]
Yes, this works. 

Unfortunately HKT export is one-way. We have no way of importing it so your only option is to use the existing HKTs.
