### ISSUE TITLE
Let user pick default options for icon render

### ISSUE THREAD

**Issue by TheWizardLizard** [enenra/space-engineers-utilities#204]
Low priority, but the option to set default angles, zoom, and maybe position in the icon render mode would be really nice, because, as my weapons are built for WeaponCore, the models are often built with +Y being forward, which often has the camera in icon render mode facing the back of the block, so default options would be nice.

**Comment by enenra** [comment]
Realistically, this is not going to happen as it would require a bunch of work trying to do something I'm not sure is possible for fairly little benefit.  Going to close this.
