### ISSUE TITLE
Possible issue with model prefixing and LOD pathing

### ISSUE THREAD

**Issue by TheWizardLizard** [enenra/space-engineers-utilities#216]
new LG_ and SG_ prefixes may not be passed to mwm data, leading it to not find its LOD models

update:
https://discordapp.com/channels/125011928711036928/161758345856811008/749768889738723468

https://discordapp.com/channels/125011928711036928/161758345856811008/749771192692506764

**Comment by enenra** [comment]
SG_ and LG_ prefixes are actually already accounted for by the code, this is luckily not an issue. The LOD placement issue is a separate one.
