### ISSUE TITLE
[2.9] Material names get cut off in selector

### ISSUE THREAD

**Issue by TheWizardLizard** [enenra/space-engineers-utilities#218]
Due to some changes in Blender 2.9, the material selector will now tell you where a material originates from, resulting in a lot of cutoff:

![image](https://user-images.githubusercontent.com/17933206/92060149-0d5c8800-ed61-11ea-94d3-a6d5fc4a995d.png)

Im not even sure how to fix this one.

**Comment by enenra** [comment]
Unfortunately I have no influence on that widget. We'll have to take this to to the Blender issue tracker.
