### ISSUE TITLE
strange export issue

### ISSUE THREAD

**Issue by stonelords** [enenra/space-engineers-utilities#219]
So after i flipped the normal on the front part of my cannon barrel when ever i export that model now it just exports the barrel part and then the main and base1 scene it creates the main collection again.

Log of the error
![unknown](https://user-images.githubusercontent.com/64538345/92289748-6cf59780-ef09-11ea-87eb-0217b2bcc1eb.png)

**Comment by enenra** [comment]
Fixed with latest commit.
