### ISSUE TITLE
Anything you can regarding the advanced door build stages issue

### ISSUE THREAD

**Issue by chipstix213** [enenra/space-engineers-utilities#223]
To correctly make an advanced door you have to have a file for each build stage with identically named subpart dummies blender hates this and will add 001 etc to the new ones. Don't think you can do anything but just in case.

**Comment by TheWizardLizard** [comment]
I believe all empties will have their duplicate ID's (.00x numbers) stripped on export, per commit https://github.com/enenra/space-engineers-utilities/commit/6ac87b6e6cf88ec8d249dd08c5a733ef2bca4cfa

**Comment by chipstix213** [comment]
in that case, he may have already solved the issue. ill experiment and report back.
