### ISSUE TITLE
Highlighting Multiple Meshes

### ISSUE THREAD

**Issue by AViegarien** [enenra/space-engineers-utilities#228]
I'm in the process of converting several models that include both doors and advanced doors from Harag's plugin to this system. The process works well except if I need to change the highlights on the doors,or make new ones. There was a way (though you had to mess with the python console) to assign multiple meshes/subparts to be highlighted by a detector. However I've been unable to accomplish the same effect with this plugin. I know Harag said there's some big limiting factor in the UI in Blender that prevented it from being a simple click and choose many meshes, but is there some sort of workaround that can be (or is) available in this plugin?

**Comment by enenra** [comment]
Can you not just parent the meshes that are to be highlighted together and then set the parent mesh as the highlight object?

Can you give me an example of a vanilla model that uses this functionality?

**Comment by AViegarien** [comment]
I guess I shouldn't have said meshes, I should have said something like subpart empties maybe? I would say a door would do it since the left and right doors are subpart empties and are highlighted together when you look at them in game.

I did think to try parenting the subparts into one empty and trying to highlight the parent empty but got the yellow box instead. I can try it again and see if it does anything.

Here is the thread I used to remind me how to link multiple subparts to one detector - https://forum.keenswh.com/threads/q-does-advanced-door-supports-new-highlight-feature.7380529/#post-1286945787

I can send you a blend file of one of the advanced doors that exports properly since it was converted with the property already from Harag's plugin.
[PassageTopDoor.zip](https://github.com/enenra/space-engineers-utilities/files/5299261/PassageTopDoor.zip)

**Comment by enenra** [comment]
Hmm I see. This is certainly possible to implement but it'll likely require me to rework the system quite a bit. I'll look into how to go about it.

**Comment by AViegarien** [comment]
ah, that's unfortunate. At least if I don't change the subpart names and such it'll still export so I can at least use it for existing files I have (which has been my main project for the last week). I'm really enjoying the plugin, thanks for all your hard work.

**Comment by enenra** [comment]
0.9.95 will include the ability to edit the custom properties of the empty directly to add multiple objects as a reference. This should be a stopgap measure until I can find a way to handle it via a proper UI but if we're being real, it's used so infrequently that it may just stay that way.
