### ISSUE TITLE
mwm converter has some mesh distortion on very large blocks

### ISSUE THREAD

**Issue by AutoMcDonough** [enenra/space-engineers-utilities#230]
smaller details which seem fine on smaller blocks become distorted when far from the origin. Even large things seem to have some error but it is harder to notice because the error becomes a smaller % of the shape.
Attaching a few pictures so you can see what I mean. Small diameter wires which should appear smooth and some hex bolts which is regular polygon.
These shapes are ~40m from the origin. (This part is 42 large blocks long)

![20201007171208_1](https://user-images.githubusercontent.com/3020791/95521425-7ace8a80-0997-11eb-9a7a-4b2cbc8afbf1.jpg)
![20201007171220_1](https://user-images.githubusercontent.com/3020791/95521434-802bd500-0997-11eb-884d-807584b5a963.jpg)

**Comment by enenra** [comment]
Unfortunately I don't have any insight into MWMB so this will have to be handled by Stollie. 

There is a chance that this might actually have to be handled by Keen directly even.

**Comment by AutoMcDonough** [comment]
I've manage to mitigate the issue in this case by moving the entire block closer to the origin and using a 30m offset in the sbc file, so it can wait for Stollie to finish classes. :)

**Comment by enenra** [comment]
I'm "transferring" this issue to the MWMB repo since it's not a SEUT issue. :)
https://github.com/cstahlhut/MWMBuilder/issues/5
