### ISSUE TITLE
CTD when using any suet side panel features after un-enabling and re-enabling plugin version 0.9.95

### ISSUE THREAD

**Issue by GenericOverlord** [enenra/space-engineers-utilities#244]
using any of the following side panel functions 
![image](https://user-images.githubusercontent.com/77060025/103774870-29c94380-5025-11eb-82ca-0fa74f502a98.png)
results in a Crash to  Desktop without warning or message.

**To Reproduce**
1.Load blank .blend disable/un-enable suet plugin in blender preferences
2. re-enable suet
3. load previous .blend files that where previously using SUET
4. use side panel buttons
5. CTD

**Expected behavior**
the Side panel buttons to perform there natural function as they did before, e.g. icon render bringing up the camera lighting etc.

**Versions**
 - SEUT version 0.9.95
 - Blender version: 2.91.0

**Comment by enenra** [comment]
Cannot reproduce this issue so far. I recommend you try reproducing it again once the next dev version / the full version of 0.9.95 is out.
