### ISSUE TITLE
Missing Collision Settings for Door-type Blocks (Two Box Types?)

### ISSUE THREAD

**Issue by Harbinger-Ace** [enenra/space-engineers-utilities#247]
**EDIT:** There is currently a workaround for all the hangar door issues highlighted here. In the physics settings:
- Set mass to 1 kg
- Uncheck "Dynamic"
- Check "Animated"
- Use Blender's defaults for everything else.

Additionally, all door empties must be rotated 180° on the Z axis. Do _not_ apply rotation!
Using a convex mesh shape works with these settings. Box collisions may work, but convex mesh is easier to customize.

This post will remain for the other apparent box type, or whatever this collision form is.

The box-type collision appears to come in two varieties. The only distinguishing factor between them, at least in Space Engineers, is that one shows up as a single blue box, while the other appears as two distinct boxes despite being a single collision mesh. When a box collision is set up in SEUT, only the single-box collision type is generated. This type causes significant issues with subpart collisions.

When using the single-box type, the subpart collisions will rotate uncontrollably, and violently interact with other grids they come into contact with. This also occurs when the subparts are extended:

![Roll1](https://user-images.githubusercontent.com/78501105/106792156-a7737580-660a-11eb-93fd-2640a7a98efa.png)

As that image may be difficult to make out, here is an example when using the default (no selected shape) option; these collisions would not normally collide, but the same issue is present:

![Roll2](https://user-images.githubusercontent.com/78501105/106792276-c7a33480-660a-11eb-9f35-85a08c0eec59.png)

The double-box is hard to showcase, since the second box is almost always obscured inside of a visible mesh. This is the best image I have been able to get. Just to reiterate, this is the box type which allows door collisions to work correctly:

![CollisionDoubleBox](https://user-images.githubusercontent.com/78501105/106792419-f3beb580-660a-11eb-91a6-511f3c70fa1d.png)

My [Armored Hangar Doors](https://steamcommunity.com/sharedfiles/filedetails/?id=2230891848) mod exhibits the rolling issue. Whenever the door subparts come into contact with another grid, are shot with any bullet weapon, or are placed down using creative tools/mode, the collisions will exhibit the showcased problem.

 - SEUT version: 0.9.94 (Remains in 0.9.96)
 - Blender version: 2.91 (Remains in 3.0)

**Comment by enenra** [comment]
This is caused by the way the empty is placed and which collider types are used and not a bug with SEUT itself. 
Details here: https://semref.atlassian.net/wiki/spaces/tutorials/pages/10944513/Create+Collision+Model+Tutorial#Special-Note%3A-Collisions-on-Subparts
