### ISSUE TITLE
Problem with collision model.

### ISSUE THREAD

**Issue by BE-Arbiter** [enenra/space-engineers-utilities#249]
The collision in Blender doesn't match with the one in game :

In Blender:
![image](https://user-images.githubusercontent.com/40821489/107839900-2dcc4c00-6daf-11eb-8d8e-f66941248e9d.png)

In Game:
![image](https://user-images.githubusercontent.com/40821489/107839894-2016c680-6daf-11eb-8435-930e0f5eb856.png)

**Comment by BE-Arbiter** [comment]
Apparently it always center the collision model:
Blender:
![image](https://user-images.githubusercontent.com/40821489/107840069-f4e0a700-6daf-11eb-8512-5fdcaa264a49.png)

Game:
![image](https://user-images.githubusercontent.com/40821489/107840073-01fd9600-6db0-11eb-894f-f713de874830.png)

**Comment by enenra** [comment]
Hi, please attempt the following:

1. Remove rigidbody from your collision meshes.
2. Apply transformation to your collision meshes.
3. Re-export and test ingame after a game restart. (rigidbody will be applied again automatically)

Oftentimes the collision meshes' rigidbody will not move correctly if the mesh is altered after it has been enabled. That is usually the cause for this issue.

**Comment by BE-Arbiter** [comment]
Didn't seems to work...
It's a cube primitive that I resized and converted to tri.
I don't see any transformation to the mesh, but may be missing something, I'm by no mean an expert at blender ^^.

Here is the blend file : 
[Small.zip](https://github.com/enenra/space-engineers-utilities/files/5975723/Small.zip)

**Comment by BE-Arbiter** [comment]
Nevermind, I found out that was missing a translate transformation.

Thank you very much for your time :)
