### ISSUE TITLE
Add error handling for hctfiltermanager.dll

### ISSUE THREAD

**Issue by enenra** [enenra/space-engineers-utilities#250]
https://discord.com/channels/125011928711036928/161758345856811008/803959229895278642

```cs
Command: D:\SEmod\SEUT\Tools\Havok\HavokContentTools\hctStandAloneFilterManager.exe -t -s C:\Users\timka\AppData\Local\Temp\space_engineers_qvbiaeu6.hko -p C:\Users\timka\AppData\Roaming\SpaceEngineers\Mods\Compound LCD\Models\PanelCorner.hkt C:\Users\timka\AppData\Roaming\SpaceEngineers\Mods\Compound LCD\Models\PanelCorner.hkt 
Error: Load failed
Could not find hctFilterManager.dll.
```

**Comment by enenra** [comment]
Error handling is implemented and working, SEMREF entry has been created.

**Comment by VictorScar** [comment]
> https://discord.com/channels/125011928711036928/161758345856811008/803959229895278642
> 
> ```cs
> Command: D:\SEmod\SEUT\Tools\Havok\HavokContentTools\hctStandAloneFilterManager.exe -t -s C:\Users\timka\AppData\Local\Temp\space_engineers_qvbiaeu6.hko -p C:\Users\timka\AppData\Roaming\SpaceEngineers\Mods\Compound LCD\Models\PanelCorner.hkt C:\Users\timka\AppData\Roaming\SpaceEngineers\Mods\Compound LCD\Models\PanelCorner.hkt 
> Error: Load failed
> Could not find hctFilterManager.dll.
> ```

Hello! If reinstalling Havok doesn't help, how do you resolve this?
