### ISSUE TITLE
Ability to define a mod folder & related changes

### ISSUE THREAD

**Issue by enenra** [enenra/space-engineers-utilities#262]
This is mainly for brainstorming of what this change would entail.

1. Allow users to define a mod folder per scene. (should it be an option for the export folder?)
2. Derive Data and model, texture folder from mod folder.
3. Place respective files in those folders automatically.
4. Update Data-files rather than creating new ones.

**Questions**
* How are subfolders handled? Do users define into which subfolders SBCs, models, etc. are placed?
* How are SBCs handled? Should multiple blockdefs be placed into one file? Maybe only small and large grid versions?

**Comment by Kinthamen** [comment]
Sounds like this could benefit from a publish button. 
So, users can set an export folder and the actual SE mods folder. While working on the project they can export/save revisions of the mod to the export folder. Once ready, press publish and it is sent directly to their SE mod folder.
