### ISSUE TITLE
Distortion on sub-parts when exporting on 0.9.96 Alpha 5

### ISSUE THREAD

**Issue by Qarannia** [enenra/space-engineers-utilities#284]
**Describe the bug**
I made a turret in Blender. It has three scenes; the main body, azimuth sub-part and elevation subpart. The version of SEUT was 0.9.96 Alpha 5 using the SEUT auto updater addon in Blender.

**To Reproduce**
1. Make turret model with sub-parts as per the attached Blender file.
2. Export using auto updated SEUT 0.9.96 Alpha 5.
3. At the time of the issue I had only made one of the two turrets on the model and had not included any collision model.
4. Export occurred without error, producing the expected three MWM files.
5. Files placed in local mod storage folder that contained other working turrets exported months ago.
6. SE run with mod in world.
7. Behaviour as per screenshot(s) on placing model.

**Expected behavior**
Turret would rotate and elevate the same as all my previous turrets.

**Screenshots**
The turret, which is round, completely distorted on rotating and elevating, and would fire at a random point in space even when a WC target was selected. For some reason, it wouldn't let me upload the screenshot to GitHub; it kept giving an error, so I have included the screenshot with the BLEND file in DM.

**BLEND file**
I have DM'ed you my BLEND file on Discord.

**Versions (please complete the following information):**
 - SEUT version [e.g. 0.9.96 Alpha 5 using the auto updater]
 - Blender version: [e.g. 2.93.3 Steam version]

**Additional context**
On a hunch from something KillerBee said on Discord about exporting, I went back to Blender and removed the SEUT and auto updater addons. I then installed SEUT manually again using the 0.9.95 zip file I had downloaded previously from GitHub. Once I did this, I exported the model again and it worked flawlessly first time. I also had Pilfit check my model personally when it was giving the error and he couldn't find anything wrong with the way I had my sub-parts, etc. set up.

I wondered if something had happened during either a SEUT auto update or a Blender update from Steam that had somehow corrupted something but I cannot confirm this.

**Comment by enenra** [comment]
https://discord.com/channels/@me/766013322859773962/878201438608687125 related model. (link won't work for anyone but you and me btw.)

**Comment by enenra** [comment]
The muzzle empties have a size that is set to > 1.0 (0.2) - this is known to cause issues. Please try using 1.0 for those for the next test with the current dev version. (once you get around to it)

**Comment by Qarannia** [comment]
Once I get my modding rig back I will give this a test.

**Comment by enenra** [comment]
Subpart distortion doesn't seem to appear anymore so I'm closing this now. We'll handle the empty issue separately.
