### ISSUE TITLE
Build Sequence LOD collections should support BS1_LOD1-BS3_LOD1 to match existing models in the SDK

### ISSUE THREAD

**Issue by skingnet** [enenra/space-engineers-utilities#290]
**Describe the bug**
The SEUT collections seem to be off for the detailed build stages and need to be adjusted to match the SDK models  

**To Reproduce**
Create a new blend file and initialize SEUT
There is only 1 build sequence LOD by default BS_LOD1 
Use Create Collection to add two more BS LODs... (SEUT adds BS_LOD2, BS_LOD3)  
and do any full import with build stage LODs 
There are never multiple LOD distances of the same build stage (BS_LOD1, BS_LOD2, BS_LOD3)
There are usually at least one BS1_LOD1 but often there are BS2_LOD1 and BS3_LOD1 models which SEUT cannot handle
I have to use a batch file to rename my models, not even sure if that will work correctly tbh

**Expected behavior**
The default collection BS_LOD1 to be renamed to BS1_LOD1 
Add Collection should add to the BS# not the LOD# when adding new collections (BS2_LOD1, BS3_LOD1)

**Screenshots**
I will add if this doesn't explain it

**BLEND file**
same here, happy to provide an example but not sure it's necessary

**Versions (please complete the following information):**
 - SEUT version 0.9.95
 - Blender version: 2.93

**Additional context**
If this has already been addressed I apologize, I looked for the problem and didn't see anything open regarding this.  As a side note, the imported LOD distances are not accurate either and will prevent export until you manually change them.

I love these tools, thank you for making them and providing them to us, I appreciate any consideration you give this.

**Comment by skingnet** [comment]
I have tried to rename the collections to match the model I imported, but SEUT renamed everything back to the names it created when I exported it

**Comment by enenra** [comment]
Hi! Thanks for the report.

Unfortunately that is not a bug so much as just a limitation with the way SEUT is currently set up. Changing the system to allow multiple LODs per BS would have made the setup much more complex than it already is. 

I might add this in the future, but it's not among my immediate plans.

**Comment by skingnet** [comment]
That's the problem, when you add in collections it looks like it wants you to make multiple LODs for BSs (BS_LOD1, BS_LOD2, etc) but it should only allow 1 LOD for each BS and create a new LOD1 for the next BS# when you add a new BS LOD...

So maybe instead if you just made the default collections match existing model implementations (BS1_LOD1, BS2_LOD1, BS3_LOD1) and include them in the start and adjust the scripts to export them, we'd be good.
