### ISSUE TITLE
Importing model made in 2.79 using Keens Materials and Harags Plugin doesnt write to XML correctly.

### ISSUE THREAD

**Issue by cstahlhut** [enenra/space-engineers-utilities#30]
Step 1.) Open a model .blend created in 2.79 using Harag's plugin that also uses Keens materials.
Step 2.) Link Matlib libaries.
Step 3.) Export.
Step 4.) Bug - Nothing written in XML for linked libraries that match the material names.

Further testing required. Test blend file attached.

[DailyNeeds_Manufacturing.zip](https://github.com/enenra/space-engineers-utilities/files/4074221/DailyNeeds_Manufacturing.zip)

**Comment by enenra** [comment]
MatLib libraries didn't appear to be linked (I checked), thus no materialrefs, and the materials didn't have the nodes named to the addon's requirements, hence no custom material entries either.

This is likely unavoidable and will just require people to remap to library materials.
