### ISSUE TITLE
NG and Alphamask Textures plugged in wrong for female materials

### ISSUE THREAD

**Issue by speaker-60** [enenra/space-engineers-utilities#314]
Just noticed that the NG and AlphaMask textures are plugged in wrong for both the female face and eyebrow materials

The nodes are named correctly but the wrong textures are set in the nodes

**Comment by enenra** [comment]
Thanks for the report, I'll look into it!

**Comment by enenra** [comment]
Fixed in SEUT Assets 0.6.0 - you should receive an update notification in addon preferences.
