### ISSUE TITLE
character scene has error with missing collections 

### ISSUE THREAD

**Issue by chipstix213** [enenra/space-engineers-utilities#319]
When changing between 'block' to 'character' then 'animation' and back I loose collections that don't come back

when exporting you get error like this https://discord.com/channels/657941006397734912/670912695788371979/934090060226256947

**To Reproduce**
1. select character scene type
2. set up export locations 
3. try exporting any mesh with valid uv & materials

**Comment by enenra** [comment]
The bug here is not the collections disappearing - that's intended and they can be brought back by using "Recreate Collections", but rather that the exporter can't properly handle collections not existing. Will investigate

**Comment by chipstix213** [comment]
Recreate collections doesn't appear on all scene types. Swapping between character and animation types removes LODs which I would expect but you have to go back to block to use recreate button
