### ISSUE TITLE
Export of scenes failing

### ISSUE THREAD

**Issue by Zardo1** [enenra/space-engineers-utilities#329]
![image](https://user-images.githubusercontent.com/67872601/163389753-fbda2c8d-6c85-44d6-a632-db66b2347545.png)

Switched to the beta branch to combat the build state collisions but for some reason exports are not working. Unsure of what i can provide to help fix this- :)

**Comment by enenra** [comment]
I've fixed this already internally. Will be contained in 1.0.0-beta.3
