### ISSUE TITLE
No Mat Libs

### ISSUE THREAD

**Issue by Geocube101** [enenra/space-engineers-utilities#342]
**Describe the bug**
The shader editor panel (reached with 'N') has no material library section. There is an area to import and export but not link. I'm not sure if this is because of the location of my game folder and assets folder (both located in a second drive) or a texture conversion failure. Every time I do attempt to convert game textures into the asset folder, I get a series of errors indicating "the system could not find the path specified." Everything else is present and works as expected; I just can't get the materials and textures from the game. Even when creating a new SEUT material first, there's still no mat lib section.

**To Reproduce**
N/A

**Expected behavior**
Expected the material section as shown [here](https://semref.atlassian.net/wiki/spaces/reference/pages/6095000/SEUT+Shader+Editor)
and for Blender to lock up for a decent length of time (as stated it should) for the texture conversion.

**Screenshots**
[Missing Material Libraries](https://drive.google.com/file/d/12mpB8mvp7nIyceOI00KoyCD6Q9-V5EwK/view?usp=sharing)
[Conversion Errors](https://drive.google.com/file/d/12W8FozI_thUglXCXGnqkM6TKn3sQzULs/view?usp=sharing)

**BLEND file**
The issue appears to be during installation as every SEUT scene I create is missing the mat lib section.

**Versions (please complete the following information):**
 - SEUT version 0.9.96
 - Blender version: 3.2.2

**Additional context**
Both the Space Engineers game directory, assets folder (as specified in the addon config), and the addon are located in a second drive (Drive letter is "X")

**Comment by enenra** [comment]
Hi, you're experiencing two separate things.

1. The Material Library in the Shader Panel does no longer exist, it is now handled differently. What guide are you going by? Because the official one should have been updated.
2. The conversion errors. These are caused by "SpaceEngineers" being in your folder name I'm pretty sure. 

I would recommend you update to the 1.0.0-beta.5 straight away, as it contains some good fixes. I'm not entirely sure but I think it might resolve 2. as well, though it's probably generally a good idea to rename that folder since it won't only contrain materials but other things as well (hence the recent rename to *assets*.

**Comment by Geocube101** [comment]
Thanks, will update to latest beta and rename my assets folder.
The guide I'm using is: https://semref.atlassian.net/wiki/spaces/reference/pages/6095000/SEUT+Shader+Editor

**Comment by Geocube101** [comment]
Updated to latest beta (1.0.0-5) and changed assets folder (now "X:\Blender\materials\assets"). Conversion still displays the same error message (with updated path).

**Comment by enenra** [comment]
Hm, unfortunately that is also something that I cannot reproduce and thus is very difficult to fix. Could you possibly try pausing any antivirus you may have running temporarily and try it again? That's currently my only guess.

**Comment by Geocube101** [comment]
Ok. No change but do you have blender from blender.org or from Microsoft store? Not sure if they're different but I'll give the "blender.org" one a try.

**Comment by Geocube101** [comment]
Issue seems to be with blender downloaded from Microsoft app store. Conversion seems to be running just fine on "blender.org" version.

**Comment by enenra** [comment]
Ah yes that does make sense. Thanks for the report back. I completely forgot that MS store Blender was even an option. Likely something to do with permissions working differently there.
