### ISSUE TITLE
Empties lose custom properties when exporting 

### ISSUE THREAD

**Issue by chipstix213** [enenra/space-engineers-utilities#356]
**Describe the bug**
Attempting to use Digi's particle script it became apparent that custom properties were not exported
The script relies on being able to enter custom string properties into the model 

**To Reproduce**
See conversation here https://discord.com/channels/125011928711036928/161758345856811008/1067040429511553024

**Expected behavior**
https://discord.com/channels/125011928711036928/161758345856811008/1067057495652171846

**Screenshots**
See discord 

**BLEND file**
Available if required

**Comment by enenra** [comment]
Relevant code: https://github.com/enenra/space-engineers-utilities/blob/master/space-engineers-utilities/export/seut_custom_fbx_exporter.py#L154-L163
