### ISSUE TITLE
SEUT material import does not work with Blender 3.5 and SEUT 1.1.0-alpha.2

### ISSUE THREAD

**Issue by ribera1945e** [enenra/space-engineers-utilities#364]
**Describe the bug**
Material import function of SEUT1.1.0-alpha2 does not work properly in Blender3.5.

**To Reproduce**
1. Prepare the latest version of Blender 3.3.5.
2. Install SEUT1.1.0-alpha.2 in Blender.
3. Open the shading tab with the attached .blend.
4. Press SEUT's Import Materials in any object's shader editor.
5. I am getting the error in the attached image. No materials are imported.
Note: The attached .blend file has been developed somewhat after self-solving the error, so I don't know if the same error will occur.

**Expected behavior**
Materials are imported correctly without error.

**Screenshots**
![image](https://user-images.githubusercontent.com/72236825/229767353-90dc7b1d-61cb-4141-a59c-525f7e223172.png)

**BLEND file**
https://drive.google.com/file/d/1W3YrRF2tGYcVzjhA7drRUcdFzKFwfQjv/view?usp=sharing

**Versions (please complete the following information):**
 - SEUT version [1.1.0-alpha.2]
 - Blender version: [3.3.5]

**Additional context**

**Comment by enenra** [comment]
I'm going to need some additional information on this issue.

1) What Blender version are you using? The title indicates 3.5 but the content lists 3.3.5, which would be a version of Blender 3.3 , not 3.5.

2) You're running import materials but what are you running it on? What file did you attempt to import materials from? If it's not a file in the SDK or the standard SEUT Assets, could you provide it?

**Comment by enenra** [comment]
Assuming this was fixed with the latest patch.
