### ISSUE TITLE
uncaught error: collection not existing

### ISSUE THREAD

**Issue by enenra** [enenra/space-engineers-utilities#37]
![img](http://protogen.ga/p/jrftgTkLCp.png)

That shouldn't be possible 

It was without any of the collections, when hitting big export button.

possibly connected to not having any collections at all? - no, not that because it happens with collections too.

**Comment by enenra** [comment]
This might be resolved now with all the reworks.

**Comment by TheWizardLizard** [comment]
Im going to consider this resolved, cause you cant hit export without the collections
