### ISSUE TITLE
Exporting A model with Large > small Breaks Weaponcore Turrets

### ISSUE THREAD

**Issue by lAimBotl** [enenra/space-engineers-utilities#374]
Exported Models subparts shrink when aiming using WeaponCore.

If you have it set to "Grid Scale = Large"
and you make a turret with subparts, and "Grid Export = Small", when you set it up for use with Weaponcore,
WC will scale the turrets when aiming. (Does not happen if you export "Grid Scale = Small" with "Grid Export = Small")

**Expected behavior**
Models exported in "Grid Export = Small" with "Grid Scale = Large" should be the same as exporting a model in "Grid Export = Small" with "Grid Scale = Small".

**Screenshots**
![GridSizeLargeSmallExport](https://github.com/enenra/space-engineers-utilities/assets/10777735/82355428-1f9e-4bcd-abe2-c005f1fc44a3)

**BLEND file**
If applicable, provide a BLEND file in which the problem can be reproduced. If you prefer to not share your BLEND file publicly, please state so and we will contact you privately.

**Versions (please complete the following information):**
 - SEUT version [1.1.0]
 - Blender version: [3.5.1]

**Additional context**
Weapons Exported with "GE = Small" "GS = Small" work fine with Weapon-core.
I am guessing it doesn't apply stuff or something when it scales it to SG?

**Comment by enenra** [comment]
Yes, anything that changes the size of empties on export is going to break turret targeting. Large to small export is not really suitable for anything with subparts in the first place tbh.

The question really is how to surface this best to the user.
