### ISSUE TITLE
Linked objects causing blender to hang.

### ISSUE THREAD

**Issue by Pathogenex** [enenra/space-engineers-utilities#377]
**Describe the bug**

When using linked copies in separate scenes. (Ctrl+L)  "Update Subparts" button will cause blender to freeze/hang. No error logs. Can send you a file with example.
Also hangs when exporting without updating subparts. 

**To Reproduce**
1. Add cube. Add two hangardoor subpart as child with cube as parent.
2. Create two more scenes (Top Right)
3. Goto second scene, add sphere and select it.
4. Ctrl+L - Link Object To Scene....
5. Bottom left select third scene.
6. goto first scene. Select each subpart and select each scene
6. Try update subparts or export scene. Blender should hang.

**Expected behavior**
Subparts updated/exported correctly without hanging.

**Screenshots**
![abc](https://github.com/enenra/space-engineers-utilities/assets/11697776/2a2c4755-e1c8-4acb-b591-cd3b60ba7c30)
![abcd](https://github.com/enenra/space-engineers-utilities/assets/11697776/d37a3a36-7768-4228-bd24-766a0b869bbe)

**BLEND file**
for an example file message me on discord - Pathogen

**Versions (please complete the following information):**
 - SEUT version 1.1
 - Blender version: 3.6.2
 - 
**Additional context**
(At a guess i would say its to do with the naming conventions of the exporter/subpartlinker using the vertexgroup name causing overwriting of previous data/ array trunication?
Would be very nice to have this fixed as currently editing individual subparts that are all identical 20+ times gets very very very repetitive. )

**Comment by enenra** [comment]
I think we discussed this briefly on discord but basically SEUT / Blender can't really deal with linked copies of objects / collections etc. I'm also not sure those can be detected at all... I'll need to look into it. It might be possible to display an error to the user if they try to export while using this feature.

**Comment by enenra** [comment]
Haven't found a good way to do this, gonna close.
