### ISSUE TITLE
getting W003 warnings on every mesh. unused materials slots not being removed.

### ISSUE THREAD

**Issue by chipstix213** [enenra/space-engineers-utilities#388]
**Describe the bug**
![image](https://github.com/enenra/space-engineers-utilities/assets/61921197/7c4dec5d-7182-4aed-8c4e-4e1def33ef8b)

**To Reproduce**
Steps to reproduce the behaviour:
1. Use import on any sdk model
2. SEUT notifications get filled with warnings.
3. observe materials listed on the mesh

**Expected behavior**
I set up a simple script to use the command 'bpy.ops.object.material_slot_remove_unused()' on each object

**Versions (please complete the following information):**
 - SEUT version 1.20
 - Blender version: 4.0.2

**Comment by enenra** [comment]
This seems to have been some kind of local / specific issue, could not reproduce.
