### ISSUE TITLE
Export options for secondary grids.

### ISSUE THREAD

**Issue by Arkolis** [enenra/space-engineers-utilities#390]
Suggestion: add additional options for small grid when exporting a large grid block.  Especially when selecting medium, it put the scale of a 1x1x1 large block to 3x3x3 not a 5x5x5, option to control this would be cool. Or an option to use the same model for large and small blocks. This should remove the duplication of blocks.

**Comment by enenra** [comment]
The case in which you'd want the same model for multiple sizes is already niche. This would be even more so. No plans to do this right now, sorry.
