### ISSUE TITLE
version 4.2 not exporting materials

### ISSUE THREAD

**Issue by chipstix213** [enenra/space-engineers-utilities#403]
**Describe the bug**
if using Blender 4.2 new release models will appear black in the game with default material and no errors in the logs. 

**To Reproduce**
normal modelling with existing gestures from the asset library  and export using Blender 4.2 and SEUT 1.2.0

**Expected behavior**
model with materials 😅

**Screenshots**
[If applicable, add screenshots to help explain your problem.](https://discord.com/channels/657941006397734912/670912695788371979/1263434174698881086)

to achieve materials loading correctly you can copy the asset as a unique material 

**Versions (please complete the following information):**
 - SEUT version 1.2.0
 - Blender version: 4.2

**Comment by enenra** [comment]
Did we have a log - game and / or SEUT - for this?

**Comment by chipstix213** [comment]
That is as the problem there wasn't anything in blender and the xml was empty

**Comment by enenra** [comment]
as in the xml placed next to the fbx? completely empty? Huh. Well at least that makes the issue obvious.
