### ISSUE TITLE
Add copy-settings button for Icon location/rotations

### ISSUE THREAD

**Issue by rayanth** [enenra/space-engineers-utilities#410]
**Describe the solution you'd like**
Would like a "Copy settings" button in the Icon Render section of SEUT that copies the Zoom/Distance/Location/Rotation settings to other scenes in the file.

**Describe alternatives you've considered**
Currently the only way to copy these settings is to duplicate the scene, which can lead to other frustrations.

**Comment by enenra** [comment]
This should be implemented as a separate button so that you can avoid overriding the orientation if you just want to update the export settings.
