### ISSUE TITLE
Smooth by Angle Modifier Breaks Texture Attaching

### ISSUE THREAD

**Issue by ari-steas** [enenra/space-engineers-utilities#413]
The automatically applied Smooth by Angle modifier prevents textures from being applied to exported models.
![image](https://github.com/user-attachments/assets/db2646cc-eb05-43fe-b0cf-cabc6b82f1a7)

**To Reproduce**
1. Apply the 'Shade Auto Smooth' tool to a mesh
2. Export the model
3. Observe the lack of textures ingame.

**Expected behavior**
Textures are attached properly to models.

**Versions:**
 - SEUT version [1.2.0, 1.2.1-alpha1]
 - Blender version: [4.2+]

**Comment by enenra** [comment]
This was fixed by my existing changes for 1.2.1-alpha.2
