### ISSUE TITLE
Exportation of subpart scenes not working.

### ISSUE THREAD

**Issue by cstahlhut** [enenra/space-engineers-utilities#46]
When doing sub-part exportation for the purposes of animation the main scene model has a dummy placed at the origin point of the sub-part and the actual mesh is moved to another scene which can then be independently rotated/transformed from the main mesh via code as a separate entity to simulate its movement in game.

The current exportation process expects certain collections to exist and will throw errors if they are not present, a further complication is that you can't create an already existing name in a subscene to adhere to collection names.

For example if the 'Main Scene' has a collection called 'Main' then the 'Subpart1Scene' will not allow a collection called 'Main' it will rename it to 'Main.001'

**Comment by enenra** [comment]
This has been fixed in the branch.
