### ISSUE TITLE
Scale HKT down according to RescaleFactor

### ISSUE THREAD

**Issue by enenra** [enenra/space-engineers-utilities#52]
HKTs aren't affected by RescaleFactor via XML, thus the model itself needs to be scaled before it is exported to match the rescalefactor (minus the additional /100 that is usually applied when writing rescalefactor)

**Comment by cstahlhut** [comment]
Coded into seut_ot_export.py by scaling up/down the blocks in the collision collection before export subprocesses run and reversing the process when sub-processes have finished.

``# Re-scale collision objects via rescale factor before export.
        for obj in collections['hkt'].objects:
            obj.scale *= context.scene.seut.export_rescaleFactor
``
