### ISSUE TITLE
model is rotated ingame

### ISSUE THREAD

**Issue by enenra** [enenra/space-engineers-utilities#57]
probably due to the weird way SE does directions, it needs to be rotated or sth.

see here: https://discordapp.com/channels/125011928711036928/161758345856811008/670006691601055805

![](https://cdn.discordapp.com/attachments/161758345856811008/670006686182014976/unknown.png)

![](https://cdn.discordapp.com/attachments/161758345856811008/670007191289331712/unknown.png)

**Comment by enenra** [comment]
it might actually be the model that is rotated, not the bounding box...

![](https://cdn.discordapp.com/attachments/539184784237133833/670013990667288626/unknown.png)

**Comment by cstahlhut** [comment]
This should be corrected in latest master push. Please test and confirm :)
