### ISSUE TITLE
MWM get placed in loose files folder instead of export folder

### ISSUE THREAD

**Issue by enenra** [enenra/space-engineers-utilities#67]
Sounds like a miscommunication on my part to @cstahlhut about how that was supposed to work.

**Comment by cstahlhut** [comment]
Needs steps to repeat/elaboration.

Every time I export with the user pref set to 'Export Folder' it's always exported to the folder designated in the add-on.

**Comment by enenra** [comment]
Fixed by @cstahlhut .
